[tool.poetry]
name = "autoarch"
description = "autoarch"
version = "0.0.1"
authors = ["Pierre-Yves Langlois"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
plumbum = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

